# Generated by Django 4.2.11 on 2024-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_userprofile_delete_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Female item', 'FM'), ('MALE item', 'MA'), ('Shoe item', 'SHOES'), ('Electronic item', 'ELECTRONICS'), ('Furniture item', 'FURNITURE'), ('Books item', 'BOOKS')], max_length=20),
        ),
    ]
